### ISSUE TITLE
Mismatched licenses

### ISSUE THREAD

**Issue by MysteryBlokHed** [supercam19/Delta#1]
The files [`Date.ini`](https://github.com/supercam19/Delta/blob/866bdb098fddc7df812cbd35c66f5f6ccbcbf999/Date/Date.ini), [`Date And Time.ini`](https://github.com/supercam19/Delta/blob/866bdb098fddc7df812cbd35c66f5f6ccbcbf999/Date/Date%20And%20Time.ini), [`Large Clock12.ini`](https://github.com/supercam19/Delta/blob/866bdb098fddc7df812cbd35c66f5f6ccbcbf999/Clock/Large%20Clock12.ini), and [`Large Clock24.ini`](https://github.com/supercam19/Delta/blob/866bdb098fddc7df812cbd35c66f5f6ccbcbf999/Clock/Large%20Clock24.ini) have metadata that states they are licensed under the CC BY-NC-SA 3.0 license, but the [`LICENSE`](https://github.com/supercam19/Delta/blob/866bdb098fddc7df812cbd35c66f5f6ccbcbf999/LICENSE) file says that the project is licensed under the Apache-2.0 license.

If the intended license is the Creative Commons license, then a plaintext version can be found [here](https://creativecommons.org/licenses/by-nc-sa/3.0/legalcode.txt). The `LICENSE` file contents would be replaced with the contents of the CC license.
If the intended license is Apache-2.0, then the metadata of the 4 files mentioned could be updated.

If I know which license is correct, I could make a quick PR to fix this.

**Comment by supercam19** [comment]
The issue has been fixed.
